# Generated by Django 6.0.6 on 2026-06-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_commandlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
