# Generated by Django 4.2.13 on 2026-06-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_server_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='key_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
