# Generated by Django 4.2.13 on 2026-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_server_key_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
