# Generated by Django 4.2.13 on 2026-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_alter_server_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
