# Generated by Django 4.2.13 on 2026-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_server_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
